ElexirApp_RSWEB/Models/Usluga.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ElexirApp_RSWEB.Models
{
    public class Usluga
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Услуга")]
        public string Name { get; set; }

        [Range(500, 10000)]
        [Display(Name = "Цена во денари")]
        public int Price { get; set; }

        [Display(Name = "Времетраење")]
        public string Duration { get; set; }

        [Display(Name = "Tип")]
        public string Benefits { get; set; }
   
        public int? FirstEmployeeId { get; set; }
        [Display(Name = "Вработен1")]
        public Vraboten FirstEmployee { get; set; }

        
        public int? SecondEmployeeId { get; set; }
        [Display(Name = "Вработен2")]
        public Vraboten SecondEmployee { get; set; }

        public ICollection<Rezervacija> Korisnici { get; set; }
    }
}

ElexirApp_RSWEB/Controllers/KorisniksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ElexirApp_RSWEB.Data;
using ElexirApp_RSWEB.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using ElexirApp_RSWEB.ViewModel;


namespace ElexirApp_RSWEB.Controllers
{
    public class KorisniksController : Controller
    {
        private readonly ElexirApp_RSWEBContext _context;

        private readonly IHostingEnvironment webHostingEnvironment;


        public KorisniksController(ElexirApp_RSWEBContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;

            webHostingEnvironment = hostingEnvironment;
        }

        // GET: Korisnicks

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string StringName, string StringSurname)
        {
            
            IQueryable<Korisnik> korisnici = (IQueryable<Korisnik>)_context.Korisnik.AsQueryable();
            if (!string.IsNullOrEmpty(StringName))
            {
                korisnici = korisnici.Where(s => s.Ime.Contains(StringName));
            }
            if (!string.IsNullOrEmpty(StringSurname))
            {
                korisnici = korisnici.Where(s => s.Prezime.Contains(StringSurname));
            }
           
            var VM = new FiltrirajKorisnici
            {
                Korisnici = await korisnici.ToListAsync()
            };

            return View(VM);
        }

        // GET: Korsniks/Details/5

        [Authorize(Roles = "Admin,Vraboten")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = await _context.Korisnik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (korisnik == null)
            {
                return NotFound();
            }

            return View(korisnik);
        }

        // GET: Korisniks/Create

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Korisniks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(KorisnikViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(model);

                Korisnik korisnik = new Korisnik
                {
                    Id = model.Id,
                    Ime = model.FirstName,
                    Prezime = model.LastName,
                    ProfilePicture = uniqueFileName
                };
                _context.Add(korisnik);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private string UploadedFile(KorisnikViewModel model)
        {
            string uniqueFileName = null;

            if (model.Picture != null)
            {
                string uploadsFolder = Path.Combine(webHostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.Picture.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Picture.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        //Oveloaded function UploadedFile for Edit
        public string UploadedFile(IFormFile file)
        {
            string uniqueFileName = null;
            if (file != null)
            {
                string uploadsFolder = Path.Combine(webHostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(file.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        // GET: Korisniks/Edit/5

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = await _context.Korisnik.FindAsync(id);
            if (korisnik == null)
            {
                return NotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, IFormFile imageUrl,[Bind("Id,Ime,Prezime,Vozrast,ProfilePicture")] Korisnik korisnik)
        {
            if (id != korisnik.Id)
            {
                return NotFound();
            }

            KorisniksController uploadImage = new KorisniksController(_context, webHostingEnvironment);
            korisnik.ProfilePicture = uploadImage.UploadedFile(imageUrl);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(korisnik);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KorisnikExists(korisnik.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(korisnik);
        }

        // GET: Korisniks/Delete/5

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = await _context.Korisnik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (korisnik == null)
            {
                return NotFound();
            }

            return View(korisnik);
        }

        // POST: Korisniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var korisnik = await _context.Korisnik.FindAsync(id);
            _context.Korisnik.Remove(korisnik);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        [Authorize(Roles = "Admin")]
        private bool KorisnikExists(int id)
        {
            return _context.Korisnik.Any(e => e.Id == id);
        }
    }
}

ElexirApp_RSWEB/Controllers/UslugasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using ElexirApp_RSWEB.Data;
using ElexirApp_RSWEB.Models;
using ElexirApp_RSWEB.ViewModel;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace ElexirApp_RSWEB.Controllers
{
    public class UslugasController : Controller
    {
        private readonly ElexirApp_RSWEBContext _context;

        public UslugasController(ElexirApp_RSWEBContext context)
        {
            _context = context;
        }


        [Authorize(Roles = "Vraboten,Korisnik")]
        public async Task<IActionResult> UslugaPoVraboten(int? id)
        {

            var vraboten = await _context.Vraboten.FirstOrDefaultAsync(m => m.Id == id);
            ViewBag.Message = vraboten;

            if (id == null)
            {
                return NotFound();
            }

            if (vraboten == null)
            {
                return NotFound();
            }
            var ElexirAppContext = _context.Usluga.Where(m => (m.FirstEmployeeId == id) || (m.SecondEmployeeId == id)).Include(c => c.FirstEmployee).Include(c => c.SecondEmployee);
            return View(await ElexirAppContext.ToListAsync());
        }

        // GET: Uslugas

        [Authorize(Roles = "Admin,Korisnik")]
        public async Task<IActionResult> Index(string Benefit)
        {
            IQueryable<Usluga> uslugi = (IQueryable<Usluga>)_context.Usluga.AsQueryable();
            IQueryable<Vraboten> vraboten = _context.Vraboten.AsQueryable();
            IQueryable<string> benefitsQuery = _context.Usluga.OrderBy(m => m.Benefits).Select(m => m.Benefits).Distinct();
           

            if (!string.IsNullOrEmpty(Benefit))
            {
                uslugi = uslugi.Where(x => x.Benefits == Benefit);
            }

           
            var viewmodel = new FiltrirajUslugi
            {

                Benefits = new SelectList(await benefitsQuery.ToListAsync()),
                Vraboten = await vraboten.ToListAsync(),
                Uslugi = await uslugi.ToListAsync()
            };
            return View(viewmodel);

            
        }

        // GET: Uslugas/Details/5

        [Authorize(Roles = "Admin,Korisnik")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usluga = await _context.Usluga
                .Include(t => t.FirstEmployee)
                .Include(t => t.SecondEmployee)
                .Include(m => m.Korisnici).ThenInclude(m=>m.Korisnik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usluga == null)
            {
                return NotFound();
            }

            return View(usluga);
        }

        // GET: Uslugas/Create

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["FirstEmployeeId"] = new SelectList(_context.Vraboten, "Id", "FullName");
            ViewData["SecondEmployeeId"] = new SelectList(_context.Vraboten, "Id", "FullName");
            return View();
        }

        // POST: Uslugas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Duration,Benefits,FirstEmployeeId,SecondEmployeeId")] Usluga usluga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usluga);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FirstEmployeeId"] = new SelectList(_context.Vraboten, "Id", "FullName", usluga.FirstEmployeeId);
            ViewData["SecondEmployeeId"] = new SelectList(_context.Vraboten, "Id", "FullName", usluga.SecondEmployeeId);
            return View(usluga);
        }

        // GET: Uslugas/Edit/5

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usluga = _context.Usluga.Where(m => m.Id == id).Include(m => m.Korisnici).First();

            if (usluga == null)
            {
                return NotFound();
            }

            var korisnici = _context.Korisnik.AsEnumerable();
            korisnici = korisnici.OrderBy(s => s.FullName);
            EditUslugaViewModel viewmodel = new EditUslugaViewModel
            {
                Usluga = usluga,
                ListaKorisnici = new MultiSelectList(korisnici, "Id", "FullName"),
                SelectedKorisnici = usluga.Korisnici.Select(sa => sa.KorisnikId)
            };

            ViewData["FirstEmployeeId"] = new SelectList(_context.Vraboten, "Id", "FullName", usluga.FirstEmployeeId);
            ViewData["SecondEmployeeId"] = new SelectList(_context.Vraboten, "Id", "FullName", usluga.SecondEmployeeId);
            return View(viewmodel);
        }

        // POST: Uslugas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, EditUslugaViewModel viewModel)
        {
            if (id != viewModel.Usluga.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewModel.Usluga);
                    await _context.SaveChangesAsync();
                    IEnumerable<int> listaKorisnici = viewModel.SelectedKorisnici;
                    IQueryable<Rezervacija> toBeRemoved = _context.Rezervacija.Where(s => !listaKorisnici.Contains(s.KorisnikId) && s.UslugaId == id);
                    _context.Rezervacija.RemoveRange(toBeRemoved);
                    IEnumerable<int> existKorisnici = _context.Rezervacija.Where(s => listaKorisnici.Contains(s.KorisnikId) && s.UslugaId == id).Select(s => s.KorisnikId);
                    IEnumerable<int> newKorisnici = listaKorisnici.Where(s => !existKorisnici.Contains(s));
                    foreach (int KorisnikId in newKorisnici)
                        _context.Rezervacija.Add(new Rezervacija { KorisnikId = KorisnikId, UslugaId = id });
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UslugaExists(viewModel.Usluga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FirstEmployeeId"] = new SelectList(_context.Vraboten, "Id", "FullName", viewModel.Usluga.FirstEmployeeId);
            ViewData["SecondEmployeeId"] = new SelectList(_context.Vraboten, "Id", "FullName", viewModel.Usluga.SecondEmployeeId);
            return View(viewModel);
        }

        // GET: Uslugas/Delete/5

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usluga = await _context.Usluga
                .Include(t => t.FirstEmployee)
                .Include(t => t.SecondEmployee)
                .Include(t => t.Korisnici).ThenInclude(t => t.Korisnik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usluga == null)
            {
                return NotFound();
            }

            return View(usluga);
        }


        // POST: Uslugas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usluga = await _context.Usluga.FindAsync(id);
            _context.Usluga.Remove(usluga);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool UslugaExists(int id)
        {
            return _context.Usluga.Any(e => e.Id == id);
        }

    }
}

ElexirApp_RSWEB/Views/Uslugas/Create.cshtml
@model ElexirApp_RSWEB.Models.Usluga

@{
    ViewData["Title"] = "Create";
}

<h1>Додади нова услуга</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Benefits" class="control-label"></label>
                <input asp-for="Benefits" class="form-control" />
                <span asp-validation-for="Benefits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstEmployeeId" class="control-label"></label>
                <select asp-for="FirstEmployeeId" class ="form-control" asp-items="ViewBag.FirstEmployeeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SecondEmployeeId" class="control-label"></label>
                <select asp-for="SecondEmployeeId" class ="form-control" asp-items="ViewBag.SecondEmployeeId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Креирај" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>

<div>
    <a style="color:black" asp-action="Index">Bрати назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ElexirApp_RSWEB/Views/Uslugas/Delete.cshtml
@model ElexirApp_RSWEB.Models.Usluga

@{
    ViewData["Title"] = "Delete";
}

<h3>Дали сте сигурни дека сакате да ја избришете услугата?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Benefits)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Benefits)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstEmployee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstEmployee.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SecondEmployee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SecondEmployee.FullName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Избриши" class="btn btn-outline-secondary" /> |
        <a style="color:black" asp-action="Index">Врати назад</a>
    </form>
</div>

ElexirApp_RSWEB/Views/Uslugas/Details.cshtml
@model ElexirApp_RSWEB.Models.Usluga

@{
    ViewData["Title"] = "Details";
}
<h1>Податоци за услугата</h1>

<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Benefits)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Benefits)
        </dd>
       
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstEmployee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstEmployee.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SecondEmployee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SecondEmployee.FullName)
        </dd>

        <dt class="col-sm-2">
            Корисници
        </dt>
        <dd class="col-sm-10">
            @foreach (var korisnik in Model.Korisnici)
            {
                <a asp-controller="Korisniks" asp-action="Details" asp-route-id="@korisnik.KorisnikId">
                    @korisnik.Korisnik.FullName
                </a> <br />}
        </dd>

    </dl>
</div>
<div>
    <a style="color:black" asp-action="Edit" asp-route-id="@Model.Id">Промени</a> |
    <a style="color:black" asp-action="Index">Врати назад</a>
</div>

ElexirApp_RSWEB/Views/Uslugas/Edit.cshtml
@model ElexirApp_RSWEB.ViewModel.EditUslugaViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Промени ги податоците</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Usluga.Id" />
            <div class="form-group">
                <label asp-for="Usluga.Name" class="control-label"></label>
                <input asp-for="Usluga.Name" class="form-control" />
                <span asp-validation-for="Usluga.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usluga.Price" class="control-label"></label>
                <input asp-for="Usluga.Price" class="form-control" />
                <span asp-validation-for="Usluga.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usluga.Duration" class="control-label"></label>
                <input asp-for="Usluga.Duration" class="form-control" />
                <span asp-validation-for="Usluga.Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usluga.Benefits" class="control-label"></label>
                <input asp-for="Usluga.Benefits" class="form-control" />
                <span asp-validation-for="Usluga.Benefits" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Usluga.FirstEmployeeId" class="control-label"></label>
                <select asp-for="Usluga.FirstEmployeeId" class="form-control" asp-items="ViewBag.FirstEmployeeId"></select>
                <span asp-validation-for="Usluga.FirstEmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usluga.SecondEmployeeId" class="control-label"></label>
                <select asp-for="Usluga.SecondEmployeeId" class="form-control" asp-items="ViewBag.SecondEmployeeId"></select>
                <span asp-validation-for="Usluga.SecondEmployeeId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Корисници</label>
                <select asp-for="SelectedKorisnici" class="form-control js-example-basic-multiple"
                        asp-items="Model.ListaKorisnici"> </select>
                <span asp-validation-for="SelectedKorisnici" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Зачувај" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>

<div>
    <a style="color:black" asp-action="Index">Врати назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    
}

ElexirApp_RSWEB/Views/Uslugas/Index.cshtml
@model ElexirApp_RSWEB.ViewModel.FiltrirajUslugi

@{
    ViewData["Title"] = "Index";
}

<body>

    <h1 style="font-style:italic;font-weight:bold; color:purple">Услуги</h1>

    <p>
        <a style="color:black" asp-action="Create">Додади нова услуга</a>
    </p>

    
    <form asp-controller="Uslugas" asp-action="Index" method="get">
        <p>
            <a><b>Филтрирај по Тип:</b></a>
            
            <select asp-for="Benefit" asp-items="Model.Benefits">
                <option  value="">Сите</option>
            </select>

            <input class="input" type="submit"  value="Филтрирај" />
        </p>
    </form>


    <table class="table input">
        <thead class="input">
            <tr  >
                <th>
                    @Html.DisplayNameFor(model => model.Uslugi[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Uslugi[0].Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Uslugi[0].Duration)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Uslugi[0].Benefits)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Uslugi[0].FirstEmployee)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Uslugi[0].SecondEmployee)
                </th>
                
                <th></th>
            </tr>
        </thead>
        <tbody >
            @foreach (var item in Model.Uslugi)
            {
                <tr  style="border-color:black;border-style:double;">
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duration)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Benefits)
                    </td>
                   

                    <td>
                        @if (item.FirstEmployeeId != null)
                        {
                            <a  asp-controller="Vrabotens" asp-action="Details" asp-route-id="@item.FirstEmployeeId"> @Html.DisplayFor(modelItem => item.FirstEmployee.FullName)</a>}
                    </td>

                    <td>
                        @if (item.SecondEmployeeId != null)
                        {
                            <a  asp-controller="Vrabotens" asp-action="Details" asp-route-id="@item.SecondEmployeeId"> @Html.DisplayFor(modelItem => item.SecondEmployee.FullName)</a>}
                    </td>
                    <td>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a style="color:black" asp-action="Edit" asp-route-id="@item.Id">Промени|</a>


                            <a style="color:black" asp-action="Delete" asp-route-id="@item.Id">Избриши|</a>
                        }
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Korisnik")))
                        {
                            <a style="color:black"  asp-action="Details" asp-route-id="@item.Id">Детали</a>
                        }


                    </td>
                </tr>
            }
        </tbody>
    </table>
    </body>