ElexirApp_RSWEB/Models/Korisnik.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ElexirApp_RSWEB.Models
{
    public class Korisnik
    {
        public int Id { get; set; }

        [Display(Name = "Име")]
        public string Ime { get; set; }

        [Display(Name = "Презиме")]
        public string Prezime { get; set; }

        [Display(Name = "Слика")]
        public string ProfilePicture { get; set; }

        [Display(Name = "Корисник")]
        public string FullName
        {
            get { return String.Format("{0} {1}", Ime, Prezime); }
        }

        public ICollection<Rezervacija> Uslugi { get; set; }
    }
}

ElexirApp_RSWEB/Controllers/RezervacijasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using ElexirApp_RSWEB.Data;
using ElexirApp_RSWEB.Models;
using ElexirApp_RSWEB.ViewModel;

namespace ElexirApp_RSWEB.Controllers
{
    public class RezervacijasController : Controller
    {
        private readonly ElexirApp_RSWEBContext _context;

        public RezervacijasController(ElexirApp_RSWEBContext context)
        {
            _context = context;
        }

        // GET: Rezervacijas

        [Authorize(Roles = "Admin,Vraboten")]
        public async Task<IActionResult> Index(string usluga)
        {
            IQueryable<Rezervacija> rezervacija = _context.Rezervacija.AsQueryable();
            IQueryable<string> uslugazapishana = _context.Usluga.OrderBy(m => m.Benefits).Select(m => m.Benefits).Distinct();
            

            if (!string.IsNullOrEmpty(usluga))
            {
                rezervacija = rezervacija.Where(s => s.Usluga.Benefits.Contains(usluga));
            }
          
            rezervacija = rezervacija.Include(r => r.Korisnik).Include(r => r.Usluga);
            var VM = new RezervacijaNaUsluga
            {
                Rezervacija = await rezervacija.ToListAsync(),
                UslugaMesto = new SelectList(await uslugazapishana.ToListAsync())
            };

            return View(VM);
        }


        // GET: Rezervacijas/Create

        [Authorize(Roles = "Korisnik,Admin")]
        public IActionResult Create()
        {
            ViewData["KorisnikId"] = new SelectList(_context.Korisnik, "Id", "Id");
            ViewData["UslugaId"] = new SelectList(_context.Usluga, "Id", "Id");
            return View();
        }

        // POST: Rezervacijas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Korisnik,Admin")]
        public async Task<IActionResult> Create([Bind("Id,UslugaId,KorisnikId")] Rezervacija rezervacija)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rezervacija);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["KorisnikId"] = new SelectList(_context.Korisnik, "Id", "Id", rezervacija.KorisnikId);
            ViewData["UslugaId"] = new SelectList(_context.Usluga, "Id", "Id", rezervacija.UslugaId);
            return View(rezervacija);
        }

        // GET: Rezervacijas/Edit/5

        [Authorize(Roles = "Vraboten,Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rezervacii = await _context.Rezervacija.FindAsync(id);
            if (rezervacii == null)
            {
                return NotFound();
            }
            ViewData["KorisnikId"] = new SelectList(_context.Korisnik, "Id", "FullName", rezervacii.KorisnikId);
            ViewData["UslugaId"] = new SelectList(_context.Usluga, "Id", "Benefits", rezervacii.UslugaId);
            return View(rezervacii);
        }

        // POST: Rezervacijas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Vraboten,Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UslugaId,KorisnikId")] Rezervacija rezervacii)
        {
            if (id != rezervacii.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rezervacii);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RezervacijaExists(rezervacii.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KorisnikId"] = new SelectList(_context.Korisnik, "Id", "FullName", rezervacii.KorisnikId);
            ViewData["UslugaId"] = new SelectList(_context.Usluga, "Id", "Benefits", rezervacii.UslugaId);
            return View(rezervacii);
        }
 
        // GET: Rezervacijas/Delete/5

        [Authorize(Roles = "Admin,Korisnik")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rezervacii = await _context.Rezervacija
                .Include(r => r.Korisnik)
                .Include(r => r.Usluga)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rezervacii == null)
            {
                return NotFound();
            }

            return View(rezervacii);
        }

        // POST: Rezervacijas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin,Korisnik")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rezervacii = await _context.Rezervacija.FindAsync(id);
            _context.Rezervacija.Remove(rezervacii);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

      
        private bool RezervacijaExists(int id)
        {
            return _context.Rezervacija.Any(e => e.Id == id);
        }
        

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> NewRezz(int id)
        {
           
            IQueryable<Usluga> uslugi = _context.Usluga;
            IEnumerable<Korisnik> korisnici = _context.Korisnik;
            

            NewRezzViewModel ViewModel = new NewRezzViewModel
            {
                Uslugi = new SelectList(await uslugi.ToListAsync(), "Id", "Benefits"),
                Korisnici = new SelectList(korisnici.OrderBy(s => s.FullName).ToList(), "Id", "FullName"),

            };
            return View(ViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> NewRezz(NewRezzViewModel ViewModel)
        {
            var usluga = await _context.Usluga.FirstOrDefaultAsync(c => c.Id == ViewModel.UslugaId);
            if (usluga == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                foreach (int korisnikId in ViewModel.SelectedKorisnici)
                {
                    Rezervacija enroll = await _context.Rezervacija
                        .FirstOrDefaultAsync(c => c.UslugaId == ViewModel.UslugaId && c.KorisnikId == korisnikId);
                    if (enroll == null)
                    {

                        _context.Add(new Rezervacija { KorisnikId = korisnikId, UslugaId = ViewModel.UslugaId });
                    }
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

       
       

        [Authorize(Roles = "Korisnik")]
        public async Task<IActionResult> KorisnikViewModel(int? id)
        {

            if (id == null)
            {
                //id = 1;
                return NotFound();
            }

            var korisnik = await _context.Korisnik.FirstOrDefaultAsync(m => m.Id == id);
            ViewBag.Message = korisnik;

            
           
            if (korisnik == null)
            {
                return NotFound();
            }
            var ElexirAppContext = _context.Rezervacija.Where(m => m.KorisnikId == id).Include(m => m.Korisnik).Include(m => m.Usluga);
            return View(await ElexirAppContext.ToListAsync());
        }


        [Authorize(Roles = "Vraboten")]
        public async Task<IActionResult> KorisniciPoUsluga(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var usluga = await _context.Usluga.FirstOrDefaultAsync(m => m.Id == id);
            ViewBag.Message = usluga;
            if (usluga == null)
            {
                return NotFound();
            }
            var ElexirAppContext = _context.Rezervacija.Where(m => m.UslugaId == id).Include(m => m.Korisnik).Include(m => m.Usluga);
            return View(await ElexirAppContext.ToListAsync());
        }


    }
}

ElexirApp_RSWEB/Controllers/VrabotensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using ElexirApp_RSWEB.Data;
using ElexirApp_RSWEB.Models;
using ElexirApp_RSWEB.ViewModel;

namespace ElexirApp_RSWEB.Controllers
{
    public class VrabotensController : Controller
    {
        private readonly ElexirApp_RSWEBContext _context;
        private readonly IHostingEnvironment webHostingEnvironment;

        public VrabotensController(ElexirApp_RSWEBContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            webHostingEnvironment = hostingEnvironment;
        }

        // GET: Vodiches

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string SearchPozicija)
        {
            //return View(await _context.Vodich.ToListAsync());
            IQueryable<Vraboten> vraboteni = _context.Vraboten.AsQueryable();
            IQueryable<string> poziciiQuery = _context.Vraboten.OrderBy(m => m.Pozicija).Select(m => m.Pozicija).Distinct();
            if (!string.IsNullOrEmpty(SearchPozicija))
            {

                vraboteni = vraboteni.Where(x => x.Pozicija == SearchPozicija);
            }

            var VM = new FiltrirajVraboten
            {
                Vraboten = await vraboteni.ToListAsync(),
                Pozicii = new SelectList(await poziciiQuery.ToListAsync())
            };

            return View(VM);
        }

        // GET: Vrabotens/Details/5

        [Authorize(Roles = "Admin,Vraboten,Korisnik")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vraboten = await _context.Vraboten
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vraboten == null)
            {
                return NotFound();
            }

            return View(vraboten);
        }

        // GET: Vrabotens/Create

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vrabotens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VrabotenViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(model);

                Vraboten vraboten = new Vraboten
                {
                    Id = model.Id,
                    Ime = model.Ime,
                    Prezime = model.Prezime,
                    Pozicija = model.Pozicija,
                    ProfilePicture = uniqueFileName
                };
                _context.Add(vraboten);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        private string UploadedFile(VrabotenViewModel model)
        {
            string uniqueFileName = null;

            if (model.Picture != null)
            {
                string uploadsFolder = Path.Combine(webHostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.Picture.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Picture.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        //Oveloaded function UploadedFile for Edit
        public string UploadedFile(IFormFile file)
        {
            string uniqueFileName = null;
            if (file != null)
            {
                string uploadsFolder = Path.Combine(webHostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(file.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }


        // GET: Vrabotens/Edit/5

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vraboten = await _context.Vraboten.FindAsync(id);
            if (vraboten == null)
            {
                return NotFound();
            }
            return View(vraboten);
        }

        // POST: Vrabotens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, IFormFile imageUrl, [Bind("Id,Ime,Prezime,ProfilePicture,Pozicija")] Vraboten vraboten)
        {
            if (id != vraboten.Id)
            {
                return NotFound();
            }
            VrabotensController uploadImage = new VrabotensController(_context, webHostingEnvironment);
            vraboten.ProfilePicture = uploadImage.UploadedFile(imageUrl);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vraboten);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VrabotenExists(vraboten.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vraboten);
        }

        // GET: Vrabotens/Delete/5

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vraboten = await _context.Vraboten
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vraboten == null)
            {
                return NotFound();
            }

            return View(vraboten);
        }

        // POST: Vrabotens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vraboten = await _context.Vraboten.FindAsync(id);
            _context.Vraboten.Remove(vraboten);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        [Authorize(Roles = "Admin")]
        private bool VrabotenExists(int id)
        {
            return _context.Vraboten.Any(e => e.Id == id);
        }
    }
}

ElexirApp_RSWEB/Views/Rezervacijas/Create.cshtml
@model ElexirApp_RSWEB.Models.Rezervacija

@{
    ViewData["Title"] = "Create";
}

<h1>Резервирај Услуга</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UslugaId" class="control-label"></label>
                <select asp-for="UslugaId" class ="form-control" asp-items="ViewBag.UslugaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="KorisnikId" class="control-label"></label>
                <select asp-for="KorisnikId" class ="form-control" asp-items="ViewBag.KorisnikId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ElexirApp_RSWEB/Views/Rezervacijas/Delete.cshtml
@model ElexirApp_RSWEB.Models.Rezervacija

@{
    ViewData["Title"] = "Delete";
}

<h3>Дали сте сигурни дека сакате да ја избришете резервацијата?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
           Услуга
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usluga.Benefits)
        </dd class>
        <dt class = "col-sm-2">
            Корисник
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Korisnik.FullName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Избриши" class="btn btn-outline-secondary" /> |
        <a style="color:black" asp-action="Index">Bрати назад</a>
    </form>
</div>

ElexirApp_RSWEB/Views/Rezervacijas/DeleteRezz.cshtml
@model ElexirApp_RSWEB.Models.Rezervacija

@{ ViewData["Title"] = "Delete"; }

<h3>Дали сте сигурни дека сакате да ја избришете резервацијата?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Услуга
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Usluga.Benefits)
        </dd>
        <dt class="col-sm-2">
            Корисник
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Korisnik.FullName)
        </dd>
    </dl>

    <form asp-action="DeleteRezz">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Избриши" class="btn btn-outline-secondary" /> |
        <a style="color:black" asp-action="KorisnikViewModel">Bрати назад</a>
    </form>
</div>

ElexirApp_RSWEB/Views/Rezervacijas/Edit.cshtml
@model ElexirApp_RSWEB.Models.Rezervacija

@{
    ViewData["Title"] = "Edit";
}

<h1>Промени резервација</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UslugaId" class="control-label"></label>
                <select asp-for="UslugaId" class="form-control" asp-items="ViewBag.UslugaId"></select>
                <span asp-validation-for="UslugaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KorisnikId" class="control-label"></label>
                <select asp-for="KorisnikId" class="form-control" asp-items="ViewBag.KorisnikId"></select>
                <span asp-validation-for="KorisnikId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зачувај" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Врати назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ElexirApp_RSWEB/Views/Rezervacijas/Index.cshtml
@model ElexirApp_RSWEB.ViewModel.RezervacijaNaUsluga

@{
    ViewData["Title"] = "Index";
}

<h1 style="font-style:italic;font-weight:bold; color:purple">Резервации</h1>

<p>
    <a style="color:black" asp-controller="Rezervacijas" asp-action="NewRezz">Направи резервација</a>
</p>

<form asp-controller="Rezervacijas" asp-action="Index" method="get">
    <p>
        <a>
            <b>
                Услуга:
                </b>
                </a>
                <select asp-for="Usluga" asp-items="Model.UslugaMesto">
                    <option value="">Сите</option>
                </select>

                <input class="input" type="submit" value="Филтрирај" />
</p>
</form>
<table class="table input">
    <thead class="input">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Rezervacija[0].Usluga.Benefits)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rezervacija[0].Korisnik.FullName)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Rezervacija) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Usluga.Benefits)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Korisnik.FullName)
            </td>
            
            <td>
                <a style="color:black" asp-action="Delete" asp-route-id="@item.Id">Избриши</a>
            </td>
        </tr>
}
    </tbody>
</table>

ElexirApp_RSWEB/Views/Rezervacijas/KorisniciPoUsluga.cshtml
@model IEnumerable<ElexirApp_RSWEB.Models.Rezervacija>
<h1>Закажани термини:</h1>
@{ var data = ViewBag.Message; }
<h1> @data.Benefits </h1>
<table class="table">
    <thead>
        <tr>
        
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @if (item.Korisnik.ProfilePicture != null)
                {
                    <img src="~/images/@item.Korisnik.ProfilePicture"
                         class="rounded-circle"
                         height="100" width="100"
                         asp-append-version="true" /> }
                else
                {
                    <img src="~/images/nopicture.jpg"
                         class="rounded-circle"
                         height="100" width="100"
                         asp-append-version="true" />}
            </td>
            <td>
                @if (item.Korisnik.FullName != null)
                {
                <a asp-controller="Vrabotens" asp-action="Details" asp-route-id="@item.KorisnikId">
                    @Html.DisplayFor(modelItem => item.Korisnik.FullName)
                </a>}
            </td>
           

        </tr>}
    </tbody>
</table>

ElexirApp_RSWEB/Views/Rezervacijas/KorisnikViewModel.cshtml
@model IEnumerable<ElexirApp_RSWEB.Models.Rezervacija>


@{ ViewData["Title"] = "KorisnikViewModel"; }


<h1 style="font-style:italic;font-weight:bold; color:purple">Закажани услуги</h1>
@{ var data = ViewBag.Message; }
<h6> @data.FullName  </h6>

<table class="table">
    <thead class="input">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Usluga.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usluga.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usluga.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usluga.Benefits)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody class="input">
        @foreach (var item in Model)
        {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.Usluga.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usluga.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usluga.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usluga.Benefits)
            </td>

            <td>
                <a style="color:black" asp-action="Delete" asp-route-id="@item.Id">Откажи резервација</a>
            </td>

        </tr>}
    
        </tbody>
</table>

ElexirApp_RSWEB/Views/Rezervacijas/NewRezz.cshtml
@model ElexirApp_RSWEB.ViewModel.NewRezzViewModel

<h1>Закажи термин:</h1>
<hr />
<form asp-action="NewRezz">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Услуга</label>
                <select class="form-control" asp-for="UslugaId" asp-items="Model.Uslugi">
                </select>
            </div>


            <div class="form-group">
                <label asp-for="SelectedKorisnici" class="control-label"></label>
                <select asp-for="SelectedKorisnici" class="form-control js-example-basic-multiple" asp-items="Model.Korisnici">
                </select>
                <span asp-validation-for="SelectedKorisnici" class="text-danger"></span>

            </div>

            <div class="form-group">
                <input type="submit" value="Зачувај" class="btn btn-secondary" />
            </div>
        </div>
    </div>
</form>


<div>
    <a style="color:black" asp-action="Index">Bрати назад</a>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    
 }

ElexirApp_RSWEB/Views/Rezervacijas/OtkaziRezz.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}